### ISSUE TITLE
Consider adding "automerge-flathubbot-prs" to flathub.json

### ISSUE THREAD

**Issue by GeorgesStavracas** [flathub/com.obsproject.Studio.Plugin.SceneSwitcher#4]
Hi @WarmUpTill, seems like you've been actively merging FlathuhBot PRs - that's great!

I just wanted to let you know that you can let FlathubBot automatically merge its own PRs (if they succeed) by adding `"automerge-flathubbot-prs": true` to `flathub.json`. This should reduce the noise on your side.

Of course, if you want to keep manually reviewing the PRs, just ignore this.

**Comment by WarmUpTill** [comment]
Ah OK - Thanks for the hint!
I will consider adding it in the future.

I am always a bit paranoid that the plugin might prevent OBS from starting, so I kind of like having a chance to test the build before the merge just in case :D

I will leave the issue open so I don't forget about this option.

**Comment by GeorgesStavracas** [comment]
Alright then - just wanted to make sure you were aware of the feature.
